# Generated by Django 4.2.2 on 2023-08-22 01:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('condition', models.IntegerField(choices=[('4', 'Excellent'), ('3', 'Good'), ('2', 'Fair'), ('1', 'Poor')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('category', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('year_set', models.TextField(blank=True)),
                ('card_num', models.TextField(blank=True)),
                ('promotional', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
