# Generated by Django 4.2.2 on 2023-08-25 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardmodel",
            name="condition",
            field=models.IntegerField(
                choices=[(4, "Excellent"), (3, "Good"), (2, "Fair"), (1, "Poor")],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
